//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ixer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_X_TRAIL_DIALOG              102
#define IDD_IXER_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDD_LPROC_MGR                   129
#define IDR_PROC_RPOP                   132
#define IDD_NEW_DLL_MGR_DLG             133
#define IDD_NEW_THREAD_MGR_DLG          134
#define IDR_DLL_RPOP                    135
#define IDR_THREAD_RPOP                 137
#define IDD_LTAB_R0HOOK                 138
#define IDD_LSSDT_MGR                   139
#define IDR_SSDT_RPOP                   141
#define IDD_LSHADOW_MGR                 142
#define IDR_SHADOW_RPOP                 143
#define IDD_LTAB_R3HOOK                 144
#define IDD_LMSGHOOK_MGR                145
#define IDD_LFILE_MGR                   146
#define ICO_CDDRV                       149
#define ICO_CLSDFLD                     150
#define ICO_DEFAULT                     151
#define ICO_DRIVE                       152
#define ICO_FLOPPYDRV                   153
#define ICO_MYCOMPUTER                  154
#define ICO_OPENFLD                     155
#define ICO_SETUPFILE                   156
#define IDR_FILE_RPOP                   157
#define IDR_MSGHOOK_RPOP                158
#define IDD_LSRV_MGR                    159
#define IDR_SRV_RPOP                    160
#define IDD_REDIT_DWVALUE               160
#define IDD_LNETWORK_MGR                161
#define IDR_NET_RPOP                    162
#define IDD_LREG_MGR                    163
#define ICO_RCOMPUTER                   164
#define ICO_RCLSDFLD                    165
#define ICO_ROPENFLD                    166
#define ICO_SZ                          167
#define ICO_DWORD                       168
#define IDR_REG_RPOP                    169
#define IDD_REDIT_SZVALUE               171
#define IDD_REG_ADDITEM                 172
#define IDR_REG_TREE_RPOP               173
#define IDD_REG_SEARCH                  174
#define IDD_LDRV_MGR                    175
#define IDR_DRV_RPOP                    176
#define IDD_LTAB_NTOS_KRNL              177
#define IDD_LABOUT_DLG                  185
#define IDC_TAB_R0HOOKS                 1000
#define IDC_PROCESS_LISTS               1001
#define IDC_STATIC_PROCESS              1002
#define IDC_MOUDLE_LISTS                1003
#define IDC_THREAD_LISTS                1004
#define IDC_TAB_MAIN_VIEW               1006
#define IDC_SSDT_LISTS                  1007
#define IDC_STATIC_SSDT                 1008
#define IDC_SHADOWSSDT_LISTS            1009
#define IDC_STATIC_SHADOWSSDT           1010
#define IDC_TAB_R3HOOKS                 1011
#define IDC_MSG_HOOK_LISTS              1012
#define IDC_STATIC_MSGHOOK              1013
#define IDC_FILE_TREE                   1014
#define IDC_FILE_LISTS                  1015
#define IDC_STATIC_FILE                 1017
#define IDC_SERVICE_LISTS               1018
#define IDC_STATIC_SERVICE              1019
#define IDC_NETWORK_LISTS               1020
#define IDC_STATIC_NETWORK              1021
#define IDC_REG_LISTS                   1022
#define IDC_REG_TREE                    1023
#define IDC_EDIT_DWDATA                 1024
#define IDC_EDIT_DWVALUE                1024
#define IDC_RADIO_HEX                   1025
#define IDC_RADIO_DEC                   1026
#define IDC_STATIC_DWNAME               1027
#define IDC_EDIT_DWNAME                 1028
#define IDC_EDIT_SZNAME                 1029
#define IDC_EDIT_SZVALUE                1030
#define IDC_EDIT_ITEMNAME               1031
#define IDC_STATIC_NAME                 1032
#define IDC_EDIT_TARGET                 1033
#define IDC_SEARCH                      1034
#define IDC_CHECK_ITEM                  1035
#define IDC_CHECK_VALUE                 1036
#define IDC_CHECK_DATA                  1037
#define IDC_CHECK_ALLWORD               1038
#define IDC_CHECK_SKIP_UPLOWER          1039
#define IDC_REG_SEARCH_LISTS            1040
#define IDC_DRVMOD_LISTS                1041
#define IDC_STATIC_DRVMOD               1042
#define IDC_TAB_NTOS_KRNL               1044
#define IDC_STATIC_REG                  1048
#define IDC_MICRO_BLOG                  1050
#define IDC_BLOG                        1051
#define IDC_EMIAL                       1054
#define IDM_REFRESH_PRO_LIST            32773
#define IDM_PRO_TERMINATOR              32774
#define IDM_PRO_KILLER                  32775
#define IDM_PROC_KILLER                 32775
#define IDM_PRO_MODULE_LIST             32776
#define IDM_PRO_THREAD_LIST             32777
#define IDM_REFRESH_MOD_LIST            32778
#define IDM_MOD_TERMINATOR              32779
#define IDM_REFRESH_TRD_LIST            32780
#define IDM_TRD_TERMINATOR              32781
#define IDM_REFRESH_SSDT_LIST           32782
#define IDM_SSDT_RESTORE                32783
#define IDM_REFRESH_SHADOW_LIST         32784
#define IDM_SHADOW_RESTORE              32785
#define IDM_REFRESH_FLE_LIST            32786
#define IDM_FLE_GRINDER                 32787
#define IDM_FILE_GRINDER                32787
#define IDM_MSG_UNHOOK                  32788
#define IDM_REFRESH_MSGHOOK_LIST        32789
#define IDM_REFRESH_SRV_LIST            32790
#define IDM_SRV_START                   32791
#define IDM_SRV_STOP                    32792
#define IDM_SRV_PAUSE                   32793
#define IDM_SRV_DELETE                  32794
#define IDM_SRV_AUTO                    32795
#define IDM_SRV_MANUAL                  32796
#define IDM_SRV_DISABLE                 32797
#define IDM_SRV_RESTORE                 32798
#define IDM_REFRESH_NET_LIST            32799
#define IDM_NET_DISCONNECT              32800
#define IDM_CONNECT_PRO_KILLER          32801
#define IDM_REG_MODIFY                  32802
#define IDM_REG_MODIFY_BIN              32803
#define IDM_REG_DELETE                  32804
#define IDM_REG_RENAME                  32805
#define IDM_NEW_ITEM                    32807
#define IDM_NEW_SZ                      32808
#define IDM_NEW_DWORD                   32809
#define IDM_REG_TREE_DEL                32810
#define IDM_TREE_NEW_ITEM               32814
#define IDM_TREE_NEW_SZ                 32815
#define IDM_TREE_NEW_DWORD              32816
#define IDM_REG_SEARCH                  32817
#define IDM_REFRESH_DRV_LIST            32818
#define IDM_COPY_DRVMEM                 32819
#define IDM_DRVMEM_DUMPER               32819
#define IDM_DELETE_DRVFILE              32820
#define IDM_DELETE_DRVFILE_REG          32821
#define IDM_COPY_DRVNAME                32822
#define IDM_COPY_DRVPATH                32823
#define IDM_GPS_DRVFILE                 32824
#define IDM_COPY_PROCNAME               32825
#define IDM_COPY_PROCPATH               32826
#define IDM_GPS_PROCFILE                32827
#define IDM_DEL_FILE                    32828
#define IDM_REFRESH_REG_LIST            32829

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         32831
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
