/*++

Copyright (c) 

Module Name:

    ixersys.h

Abstract:

    This framework is generated by QuickSYS 0.4

Author:

	<your name>

Environment:

	User or kernel mode.

Revision History:

--*/

#ifndef _IXER_H
#define _IXER_H 1


//
// A structure representing the instance information associated with
// a particular device
//

typedef struct _DEVICE_EXTENSION
{
	ULONG  StateVariable;
} DEVICE_EXTENSION, *PDEVICE_EXTENSION;

//
// Device driver routine declarations.
//

NTSTATUS
DriverEntry(
			IN PDRIVER_OBJECT		DriverObject,
			IN PUNICODE_STRING		RegistryPath);

NTSTATUS
IrpMjXTRdevCtrlRoutine(
					   IN PDEVICE_OBJECT		DeviceObject,
					   IN PIRP					Irp);

VOID
IrpMjXTRUnloadRoutine(
					  IN PDRIVER_OBJECT		DriverObject);

/* º¯ÊýÉùÃ÷ ================================================ */

BOOLEAN
IxioControl(
			 IN PVOID InputBuffer,
			 IN ULONG InputBufferLength,
			 IN PVOID OutputBuffer,
			 IN ULONG OutputBufferLength,
			 IN ULONG IoControlCode,
			 IN PIO_STATUS_BLOCK pIoStatus);


//////////////////////////////////////////////////////////////////////////
#endif
